version: '3'

services:
  nodejs:
    container_name: nodejs
    build:
      context: ./resources/node
    user: node
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
#    command: ["npm", "start"]
    tty: true
    restart: always
