version: '3'

services:
  nodejs:
    container_name: nodejs
    image: node:12
    user: node
    environment:
      - NODE_ENV=production
    ports:
      - 8000:8000
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
#    command: ["npm", "start"]
    tty: true
    restart: always
